# Generated by Django 6.0.4 on 2026-05-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_feedback_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_range',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
